# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  # lane :get_app_store_connect_api_key do
  #   # fetch api key data
  #   app_store_connect_api_key(
  #     key_id: "YS6HCWNGAX", #Your Auth key ID
  #     issuer_id: "9389fe93-4b9b-4ba5-bff5-0470887755f9", #Your Auth key Issuer ID
  #     key_filepath: "fastlane/AuthKey_YS6HCWNGAX.p8", #Auth key path
  #     in_house: false,
  #   )
  # end
  lane :release do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"
    ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "180"
    
    sigh(app_identifier: "com.lovedrop.demo")

    # increment the build number
    increment_build_number(xcodeproj: "LoveDrop.xcodeproj")

    # generate ipa file to upload
    ipa = build_app(workspace: "LoveDrop.xcworkspace", scheme: "LoveDrop", export_method: "app-store", output_directory: "build")

    # upload the build to testflight
    pilot(
      ipa: ipa, 
      skip_submission: true, 
      api_key: app_store_connect_api_key(
        key_id: "YS6HCWNGAX", #Your Auth key ID
        issuer_id: "9389fe93-4b9b-4ba5-bff5-0470887755f9", #Your Auth key Issuer ID
        key_filepath: "fastlane/AuthKey_YS6HCWNGAX.p8", #Auth key path
        in_house: false,
      )
    )
  end
end

