name: deploy


on:
 push:
   branches:   
    - Development 
   tags: [ v* ]




jobs:
 deploy_ios:
   runs-on: macos-latest
   if: "!contains(github.event.head_commit.message, 'skip ci')"
   steps:
     - uses: maxim-lobanov/setup-xcode@v1
       with:
         xcode-version: 'latest' #latest version
     - uses: actions/checkout@v2


     - name: setup ruby
       run: brew install openssl readline rbenv ruby-build


     - name: Set environment variables from project settings
       run: |
         exec .github/scripts/set-env-from-xcodeproj.sh


     - name: Import signing certificate
       env:
         SIGNING_CERTIFICATE_P12_DATA: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA }}
         SIGNING_CERTIFICATE_PASSWORD: ${{ '' }}
       run: |
         exec .github/scripts/import-certificate.sh


     - name: Import provisioning profile
       env:
         PROVISIONING_PROFILE_DATA: ${{ secrets.PROVISIONING_PROFILE_DATA }}
       run: |
         exec .github/scripts/import-profile.sh


     - name: setup xcode version
       run: |
         cd ios
         sudo xcode-select -s /Applications/Xcode_14.2.app  #latest version



     - name: Install yarn dependencies
       run: yarn



     - name: Install pod dependencies
       run: |
         cd ios && pod install



     - name: setup fastlane
       run: cd ios && bundle install
       
       
       
     - name: upload to testflight
       env:
         FASTLANE_USER: ${{ secrets.APP_STORE_CONNECT_USERNAME }}
         FASTLANE_PASSWORD: ${{ secrets.APP_STORE_CONNECT_PASSWORD }}
         APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
       run: |
         cd ios
         bundle exec fastlane release
